server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_label_logging]
        regex: enabled
        action: keep

      # Pflichtlabel, verhindert 400er in Loki
      - action: replace
        target_label: job
        replacement: docker

      # Compose-Service-Name (falls vorhanden)
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service

      # Fallback: service = Container-Name (ohne führenden Slash)
      - source_labels: [__meta_docker_container_name]
        regex: "/?(.*)"
        target_label: service

      # Praktisch für Drilldown/Explore
      - source_labels: [service]
        target_label: service_name

      # Nützliche Labels
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_image]
        target_label: image
      - source_labels: [__meta_docker_container_name]
        regex: "/?(.*)"
        target_label: container

    pipeline_stages:
      - docker: {}